// <auto-generated />
using System;
using Infrastructure.DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.DataAccess.EFCore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220806181811_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.PruebaTecnica.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("cl_contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("cl_estado")
                        .HasColumnType("bit");

                    b.Property<int>("pr_edad")
                        .HasColumnType("int");

                    b.Property<string>("pr_genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pr_identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pr_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pr_telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Domain.PruebaTecnica.Models.Cuentas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("clienteId")
                        .HasColumnType("int");

                    b.Property<bool>("cu_estado")
                        .HasColumnType("bit");

                    b.Property<int>("cu_numero_cuenta")
                        .HasColumnType("int");

                    b.Property<double>("cu_saldo_inicial")
                        .HasColumnType("float");

                    b.Property<string>("cu_tipo_cuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.ToTable("cuentas");
                });

            modelBuilder.Entity("Domain.PruebaTecnica.Models.Movimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("cuentaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("mo_fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("mo_saldo")
                        .HasColumnType("float");

                    b.Property<string>("mo_tipo_movimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cuentaId");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("Domain.PruebaTecnica.Models.Cuentas", b =>
                {
                    b.HasOne("Domain.PruebaTecnica.Models.Clientes", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId");

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("Domain.PruebaTecnica.Models.Movimientos", b =>
                {
                    b.HasOne("Domain.PruebaTecnica.Models.Cuentas", "cuenta")
                        .WithMany()
                        .HasForeignKey("cuentaId");

                    b.Navigation("cuenta");
                });
#pragma warning restore 612, 618
        }
    }
}
